name: secure_guard
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.3
  get: ^4.6.5
  liquid_swipe: ^3.0.0
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_native_splash:
  color: "#f7f6f1"
  color_dark: "#272727"
  image: assets/images/splash_images/splash-secure-guard.png
  image_dark: assets/images/splash_images/splash-secure-guard.png

android_12:
  image: assets/images/splash_images/splash-secure-guard.png
  icon_background_color: "f7f6f1"
  image_dark: assets/images/splash_images/splash-secure-guard.png
  icon_background_color_dark: "272727"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/splash_images/
    - assets/images/on_boarding_images/
